### ISSUE TITLE
Splats are all aligned along the horizontal plane

### ISSUE THREAD

**Issue by ZainlessBrombie** [hausfrau87/UE4_GPUPointCloudRenderer#2]
Hey there :)
Amazing plugin you have there. Unfortunately it does not seem to work for me, as all dots are aligned along the horizontal plane, making them invisible at eye height.
Would you know anything about that? If you need a project to reproduce let me know :)
Engine version 4.18.3
Cheers!

**Comment by ValentinKraft** [comment]
hey! do you have a screenshot of the rendering? and maybe the node setup? quite difficult to say something without some further information ;)

**Comment by ZainlessBrombie** [comment]
Hey there! Excuse my late response, I'll see that I get you a screenshot, but my suspicion is that it happened because I was in VR
