### ISSUE TITLE
Splats are triangular no matter the falloff value

### ISSUE THREAD

**Issue by DarioMazzanti** [hausfrau87/UE4_GPUPointCloudRenderer#3]
Thanks for the plugin!
Everything seems to work fine for me, but I cannot seem to make the splats round: they are always triangular.

I tried changing the falloff value, but I only seem to be able to get binary results:
- falloff values grater than 0 --> full triangle
- falloff values of 0 (or less) --> fully transparent splat

I also tried masked as well as transparent blend modes, getting the same result.
I looked into the material, and the part related to opacity does exactly what you describe in your thesis ( well, of course! :) )
Is there some setting I need to look into, or something I am forgetting?
I am working on `master_4.19` branch.

![splats_triangular](https://user-images.githubusercontent.com/19430872/61537433-7850df80-aa37-11e9-8540-df04aba4768d.PNG)

Thanks!

**Comment by ValentinKraft** [comment]
hey dario,

I would recommend to use the master branch (for UE4.21 and not UE4.19) because the older versions still might be a bit buggy ;)

let me know if that helps.

**Comment by DarioMazzanti** [comment]
Hey!
Unfortunately my team needs to stick with UE4.19, at least for some time, since we have many plugins which would require us some effort updating. 

Anyway, I slightly modified the shader and now I can see the splats as circles :)
I am using the original positioning as input for computing the round shape, instead of the UVs. I am not sure that is 100% correct - it seems to work properly though:
![workaround](https://user-images.githubusercontent.com/19430872/62452227-09ca8c00-b770-11e9-96b4-f17ce2ba24f1.jpg)

Thanks again!
