### ISSUE TITLE
Error when packaging project

### ISSUE THREAD

**Issue by StefhanHolmgrenJonas** [hausfrau87/UE4_GPUPointCloudRenderer#4]
Hi.

Thank you for your excellent plugin. Have been testing the 4.18 and 4.19 version with no problems. But the newest 4.21 version gives me initially the following error when packaging to Win64:

> ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Epic Games\UE_4.21\Engine\Intermediate\Build\Win64\UE4\Development\CurveEditor\CurveEditor.precompiled'

I tracked it down to some editor specific modules which creates issues when packaging, and then I noticed in the GPUPointCloudRenderer.uplugin file that the module "GPUPointCloudRendererEditor" is now set to "Runtime". I changed this to "editor" and now the packaging is successful.

Unfortunately, the plugin does not seem to work in the packaged game, and seems to be a problem accessing the blueprint function or something. I observe this error message in the log (I have a pawn activating a blueprint function which starts the GPUPointCloudRenderer) :

> [2019.08.05-09.22.19:010][155]LogScript: Warning: Accessed None trying to read property GPUPointCloudRenderer...

Are you able to package a project for Win64 successfully with newest version?

Thanks.

**Comment by ValentinKraft** [comment]
Hey,

actually the plugin is designed as an editor plugin and I did not test it in packaged projects, sorry!

**Comment by StefhanHolmgrenJonas** [comment]
That is unfortunate. I am doing some research and testing rendering live data in UE4 from a LiDAR, and your plugin has great potential in this area. The challenge is getting enough performance, and your plugin is very promising, but one need to be able to create a package.

Are you planning on making the plugin packagable? I think maybe it doesn't require much, since earlier versions work? I suspect modules "PropertyEditor" and "BlueprintGraph" are causing problems when packaging.

**Comment by ValentinKraft** [comment]
The problem is that I dont have much time at the moment, so I might add this later on but I dont know when I will have time for this. Of course you can always do it yourself and send me a pull request!

**Comment by ValentinKraft** [comment]
Feature added
