### ISSUE TITLE
Missing PointClouds Modules

### ISSUE THREAD

**Issue by moritzsalla** [hausfrau87/UE4_GPUPointCloudRenderer#6]
I've placed the plugin into the `Unreal Projects > MyProject > Plugins` folder. When opening the project, this error appears.

<img width="372" alt="Screenshot 2021-01-14 at 14 53 37" src="https://user-images.githubusercontent.com/42788026/104599909-9f15c380-5678-11eb-8f92-89f3ad141c94.png">

`Pointclouds could not be complied. Try rebuilding from source manually.`
I'm on `4.24.0`. Is this a versioning issue?

**Comment by ValentinKraft** [comment]
Yep, its a versioning issue. Just rebuild the plugins.
